### ISSUE TITLE
Execution of program

### ISSUE THREAD

**Issue by 007scorpio** [dafthack/PowerMeta#7]
hi am new to powershell... how do i do Invoke-powermeta because my gives me error: is not recorgnize as the name of a cmdlet, function, script file etc. :)

**Comment by dafthack** [comment]
Hey 007scorpio, just make sure the PowerMeta.ps1 file is in your current directory, run cmd.exe, then: 

powershell.exe -exec bypass
Import-Module PowerMeta.ps1

You should now be able to run the invoke commands.

**Comment by 007scorpio** [comment]
Oops my bad i found out so u can pls close this issue. Thanks

**Comment by 007scorpio** [comment]
WOrking now but it says "Invoke-Webrequest" s not recorgnize as the name of a cmdlet, function, script file etc.

**Comment by dafthack** [comment]
That is likely because you are not using PowerShell version 3 or up. Sorry, I will add that as a pre-req in the README.

**Comment by dafthack** [comment]
Added to README
